Output demo.gif

Set FontSize 24
Set Theme "Catppuccin Mocha"
Set FontFamily "FiraCode Nerd Font Mono"
Set Width 1400
Set Height 800
Set TypingSpeed 200ms

Hide
Type "nvim main.cpp"
Enter
Show

Sleep 10s

Type "5j"
Type "vib"
Sleep 2s

Set TypingSpeed 500ms
Space
Type "gd"

Set TypingSpeed 200ms
Sleep 2s

Escape
Type "jjjo"
Escape
Type "k"
Sleep 1s

Set TypingSpeed 1000ms
Type `"dp`

Sleep 10s

Hide
Sleep 1s
Type ":q!"

